<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<form class="form applyfortradeaccount"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="applyfortradeaccount_form"
      enctype="multipart/form-data"
      method="post"
      onsubmit="return myFunction2()"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
                                
                                
    <fieldset class="fieldset">
         <p><?php /* @escapeNotVerified */ echo __('Our specialist coporate and bulk pricing services are ideal for large users and/ or users with specialist needs.') ?></p><br />
        <div class="field contact_name required">
            <div class="control">
                <input name="contact_name" id="contact_name" placeholder="Your name*" title="<?php /* @escapeNotVerified */ echo __('Contact Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field name required">
            <div class="control">
                <input name="company" id="company" placeholder="Your company name*" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
	    </div>
        <div class="field email required">
            <div class="control">
                <input name="email" id="email" placeholder="Email address*" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field phone">
            <div class="control">
                <input name="phone" id="phone" placeholder="Telephone*" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" />
            </div>
        </div>
        <div class="field amount_employees">
            <label class="label" for="employee_amount"><span><?php /* @escapeNotVerified */ echo __('Amount of Employees') ?></span></label>
            <div class="control">
                <select name="employee_amount" id="employee_amount">
                    <option value="select">Select Number</option>
                    <option value="0 - 10">0 - 10</option>
                    <option value="10 - 100">10 - 100</option>
                    <option value="100 - 500">100 - 500</option>
                    <option value="500+">500+</option>
                </select>
            </div>
        </div>
        <div class="field options" style="display:none;">
            <div class="control">
                <input name="options" id="options" value="" class="input-text" type="text" />
            </div>
        </div>
        <div class="field">
                
                <?php if($block->isCaptchaEnable()): ?>
                       <div class="g-recaptcha"  name="recaptcha" id="recaptcha" data-sitekey="<?php echo $block->getPublicKey(); ?>"></div>
                    <div ><p style="
    cursor: auto;
    /* text-decoration: underline; */
    color: #9b9b9b;
    padding-left: 235px;
    font-family: Roboto,helvetica,arial,sans-serif;
    font-size: 8px;
    font-weight: 400;
    margin-top: -35px;
">by <a style="color: #9b9b9b;" rel="no-follow" target="_Blank" href="https://www.fmeextensions.com/request-for-quote-magento-2.html">Fmeextensions</a></p>  </div>
                                                  <br>
                        
                         
                <?php endif; ?>
        </div>
        
        
       
        
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/javascript">
    function myFunction2() {
        var exists = document.getElementById("g-recaptcha-response");

            if(exists == null){
                    
            }
        
             else{

            var check = document.getElementById("g-recaptcha-response").value;
           // alert(check);
                if(check=='' || check == null){
                    document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
                    return false;
                }
                else{
                    document.getElementById("recaptcha").style.border = "none";
                    return true;
                }
            }
            
   
}
</script>

<script type="text/javascript">
    require(['jquery'],
    function ($) {
        $(document).ready(function() {
                $('select#employee_amount').change(function(){
                    var _value = $(this).val();
                    if(_value != ''){
                        var _result = $('option[value="' + _value + '"]').text();
                        $("#options").val($("#options").val()+_result);
                    }
                });
        });
    })
</script>
<style type="text/css">
    
    #recaptcha {
  display: inline-block;
  position: relative;
  
  
}

</style>